[workspace]

members = [
    "archive", "bitarray",
    "cache",
    "dns",
    "encoding",
    "http", 
    "json", "json_derive",
    "protobuf",
    "redis",
    "rsgateway", 
    "tcp",
]

resolver = "2"
