[workspace]

members = [
    "archive", "bitarray", "bitarray_derive",
    "cache",
    "dns",
    "encoding",
    "http", 
    "json", "json_derive",
    "protobuf",
    "redis",
    "rsgateway", 
    "tcp", "udp",
]

resolver = "2"
