[workspace]

members = [
    "archive", "bitarray", "bitarray_derive",
    "cache",
    "dns", "dns2",
    "encoding",
    "http", 
    "json", "json_derive", "net",
    "protobuf",
    "redis",
    "rsgateway", 
    "tcp",
]

resolver = "2"
