[package]
name = "udp"
version = "0.1.0"
edition = "2021"

[dependencies]
bitarray = { path = "../bitarray" }
bitarray_derive = { path = "../bitarray_derive" }
libc = "0.2"

[profile]
[dev]
runner = 'sudo -E'