[package]
name = "archive"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"

[dev-dependencies]
rstest = "0.19.0"
criterion = "0.3"
tempfile = "3"

[[bench]]
name = "lz"
harness = false
