[package]
name = "dns2"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary-int = "1.2.7"
bitarray = { path = "../bitarray" }
bitarray_derive = { path = "../bitarray_derive" }

[dev-dependencies]
rstest = "0.19.0"