[package]
name = "json"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13"

[dev-dependencies]
rstest = "0.19.0"
pretty_assertions = "1.4.0"
criterion = "0.3"

[[bench]]
name = "parse"
harness = false
