name: "test"
on: [push]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - run: |-
          rustup component add rustfmt
          cargo fmt --check
      - run: |-
          cargo +nightly tarpaulin \
            --workspace \
            --timeout 120 \
            --out xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true