name: "test"
on: [push]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    services:
      redis:
        image: redis:7.2.5-alpine3.20
        ports:
          - 6379:6379
      httpbin:
        image: kennethreitz/httpbin:latest
        ports:
          - 9000:80
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - run: |-
          curl -v locahost:6379 || :
          curl -v redis:6379 || :
          curl -v httpbin:9000 || :
          curl -v localhost:9000 || :

      # - run: |-
      #     rustup component add rustfmt
      #     cargo fmt --check
      # - run: |-
      #     cargo +nightly tarpaulin \
      #       --workspace \
      #       --timeout 120 \
      #       --out xml
      # - name: Upload to codecov.io
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     fail_ci_if_error: true