[package]
name = "net"
version = "0.1.0"
edition = "2021"

[dependencies]
bitarray = { path = "../bitarray" }
bitarray_derive = { path = "../bitarray_derive" }
libc = "0.2"
tun-tap = "0.1"
arbitrary-int = "1.2.7"

[dev-dependencies]
etherparse = "0.15"